
export const SET_QUESTION_LIST = 'SET_QUESTION_LIST'
export const SET_COURSE_NAME = 'SET_COURSE_NAME'
export const SET_CURRENT_QUESTION = 'SET_CURRENT_QUESTION'
export const SET_CURRENT_INDEX = 'SET_CURRENT_INDEX'
export const SET_OPEN_QUESTIONS = 'SET_OPEN_QUESTIONS'
export const SET_STUDENT_ANSWER = 'SET_STUDENT_ANSWER'
export const SET_OUTPUT_DATA = 'SET_OUTPUT_DATA'
export const SET_DEBUG_DATA = 'SET_DEBUG_DATA'
export const SET_LIST_OPEN = 'SET_LIST_OPEN'
export const SET_VARIATE_ANIMATION = 'SET_VARIATE_ANIMATION'
export const SET_CLEAR_OUTPUT_AUTO = "SET_CLEAR_OUTPUT_AUTO"
export const SET_ERROR_TEST_DATA = "SET_ERROR_TEST_DATA"
export const RESET_STATE = "RESET_STATE"
export const SET_CURRENT_TEST_ORDER = "SET_CURRENT_TEST_ORDER"
export const SET_INIT_TEST_DATA_LENGTH = "SET_INIT_TEST_DATA_LENGTH"
export const SET_CHANGE_VARS_ARR = "SET_CHANGE_VARS_ARR"
export const SET_QUESTION_STATUS = "SET_QUESTION_STATUS"